### ISSUE TITLE
Create a rust implementation for fileTestSuite spec.

### ISSUE THREAD

**Issue by KOLANICH** [agrif/explode#1]
Hi. I have created a repo https://github.com/implode-compression-impls/implode_test_files made of test files taken from various libs for working with implode compression.

I have also created https://github.com/fileTestSuite/fileTestSuite specification and impls for python and C++ (the submodule is named `C` because the lib parsing the machine-readable metadata is written in C and can be used from C projects, but the most convenient part is the one automatically generating tests is written in C++ and depends on C++ libs. That one is not very good and contains some memory safety bugs).

The binary metadata format was designed to allow it be easily parsed from low-level languages. It is the primary source of info, not JSON, when processing the repo for testing purposes. The repo contains some specs in Kaitai Struct, they can (I have not tested, the KS runtime for rust is not mature enough) be useful to automatically generate a parser for the binary metadata file. But the rest of code, the one automatically converting the paths of files into test cases in unit testing frameworks, has to be written manually.

Implementing a rust impl of fileTestSuite spec would allow your project to test on wider set of tests.

Warning: the formats (and the models behind them) is not yet stable, and will likely be changed, only the most basic stuff (`raw_ext`, `processed_ext`) would likely remain as it is.

**Comment by agrif** [comment]
I'm closing this, mostly on account of it's been 2.5 years and I'm not likely to do anything in the next 2.5 years.

This is a neat idea, but I'm probably not going to implement the necessary rust to talk to these files. And, frankly, the recent business with xz makes me reluctant to accept binary blob tests without either a hard look or a very transparent source.
